version: '3'

volumes:
  db-data:

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: tail -f /dev/null
  db:
    image: postgres:13.4
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
